USE [master]
GO

CREATE DATABASE [Experis]
GO

--DROP DATABASE Experis

USE [Experis]
GO

--Tabla PRODUCTO
CREATE TABLE [dbo].[PRODUCTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](100) NULL,
	[PRECIO] [decimal](9, 2) NULL,
	[STOCK] [int] NULL,
	[FECHAREGISTRO] [datetime] NULL,
 CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--DROP PROCEDURE USP_CREATEUPDATEPRODUCTO
CREATE PROCEDURE USP_CREATEUPDATEPRODUCTO
@ID INT = 0,
@NOMBRE VARCHAR(100),
@PRECIO DECIMAL(9,2),
@STOCK INT
AS
	BEGIN
		IF(@ID = 0)
			BEGIN
				INSERT INTO PRODUCTO(NOMBRE, PRECIO, STOCK, FECHAREGISTRO)
				VALUES(@NOMBRE, @PRECIO, @STOCK, GETDATE())
			END
		ELSE
			BEGIN	
				UPDATE PRODUCTO
				SET   NOMBRE = @NOMBRE
					, PRECIO = @PRECIO 
					, STOCK = @STOCK
				WHERE ID = @ID
			END				
	END
GO

--DROP PROCEDURE USP_SEARCHPRODUCTO
CREATE PROCEDURE USP_SEARCHPRODUCTO
@ID INT = NULL
AS
	BEGIN
		SELECT  ID
			  , NOMBRE
			  , PRECIO
			  , STOCK
			  , FECHAREGISTRO
		FROM PRODUCTO	
		WHERE @ID is null or ID = @ID
	END
GO

--DROP PROCEDURE USP_DELETEPRODUCTO
CREATE PROCEDURE USP_DELETEPRODUCTO
@ID INT
AS
	BEGIN
		DELETE FROM PRODUCTO WHERE ID = @ID
	END
GO

